"""
Finding database model.
Unified flexible storage for findings generated by all OSINT modules (domain, ip, email, username, file, threat_intel).
"""
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from database.session import Base


class Finding(Base):
    __tablename__ = "findings"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    investigation_id = Column(String(36), ForeignKey("investigations.id", ondelete="CASCADE"), nullable=False, index=True)
    module = Column(String(50), nullable=False, index=True)  # domain, ip, email, username, file, threat_intel
    type = Column(String(100), nullable=False, index=True)   # whois, dns, subdomains, geoip, open_ports, metadata, etc.
    data = Column(JSON, nullable=False, default=dict)        # raw or structured result JSON
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    # Relationships
    investigation = relationship("Investigation", back_populates="findings")

    def __repr__(self):
        return f"<Finding module={self.module} type={self.type} investigation_id={self.investigation_id}>"
